version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynt
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:5000/health"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - mynt
    depends_on:
      - redis
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mysql:3306"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynt
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Anurag1234
      MYSQL_DATABASE: chat_db
    ports:
      - "3306:3306"
    networks:
      - mynt
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pAnurag1234"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  mynt:
    driver: bridge

volumes:
  redis_data:
  mysql_data:
